import{a as f,S as d,i}from"./assets/vendor-CrlV4O_2.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const m="50307425-541b949c038afe75b2e77934f",y="https://pixabay.com/api/";async function g(t){const a={key:m,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await f.get(y,{params:a})).data}catch(o){throw console.error("Error fetching images:",o.message),o}}document.querySelector(".gallery");let p=new d(".gallery a",{captionsData:"alt",captionDelay:250});function h(t){const a=t.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:n,comments:l,downloads:u})=>`
      <li>
      <a href="${s}">
        <img src="${o}" alt="${e}" />
      </a>
      <p>❤️ ${r} 👁️ ${n} 💬 ${l} ⬇️ ${u}</p>
    </li>
  `).join("");galleryEl.insertAdjacentHTML("beforeend",a),p.refresh()}function L(){galleryEl.innerHTML=""}function b(){var t;(t=document.querySelector(".loader-container"))==null||t.classList.remove("hidden")}function S(){var t;(t=document.querySelector(".loader-container"))==null||t.classList.add("hidden")}const c=document.querySelector(".form"),w=c.elements["search-text"];c.addEventListener("submit",async t=>{t.preventDefault();const a=w.value.trim();if(!a){i.warning({message:"Please enter a search term"});return}b(),L();try{const o=await g(a);o.hits.length===0?i.info({message:"Sorry, there are no images matching your search query. Please try again!"}):h(o.hits)}catch{i.error({message:"Something went wrong. Try again later."})}finally{S()}});
//# sourceMappingURL=index.js.map
