import{a as f,S as d,i as s}from"./assets/vendor-CrlV4O_2.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const m="https://pixabay.com/api/",y="50307425-541b949c038afe75b2e77934f";async function p(t){const n={key:y,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await f.get(m,{params:n})).data}catch(o){throw console.error("Error fetching images:",o.message),o}}document.querySelector(".gallery");let h=new d(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const n=t.map(({webformatURL:o,largeImageURL:i,tags:e,likes:r,views:a,comments:l,downloads:u})=>`
      <li>
      <a href="${i}">
        <img src="${o}" alt="${e}" />
      </a>
      <p>❤️ ${r} 👁️ ${a} 💬 ${l} ⬇️ ${u}</p>
    </li>
  `).join("");galleryEl.insertAdjacentHTML("beforeend",n),h.refresh()}function L(){galleryEl.innerHTML=""}function b(){var t;(t=document.querySelector(".loader-container"))==null||t.classList.remove("hidden")}function S(){var t;(t=document.querySelector(".loader-container"))==null||t.classList.add("hidden")}const c=document.querySelector(".form"),q=c.elements["search-text"];c.addEventListener("submit",async t=>{t.preventDefault();const n=q.value.trim();if(n){L(),b();try{const o=await p(n);if(o.hits.length===0){s.info({title:"Oops",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(o.hits)}catch{s.error({title:"Error",message:"Something went wrong..."})}finally{S()}}});
//# sourceMappingURL=index.js.map
